[package]
name = "vfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error = { path = "../../error" }
libcommon = { path = "../../libcommon" }
hashbrown = "0.11.*"
