[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kernel"
test = false

[dependencies]
cfg-if = "1.x.x"
error = { path = "../error" }
tock-registers = "0.7.x"
fdt-rs = { version = "0.x.x", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { version = "6.x.x" }

[features]
mach_qemu = []
mach_orangepi3 = []
